x-base-config: &base-config
    build:
        context: ../../../
        dockerfile: contrib/docker/Dockerfile.alpine
    networks:
        - internal

networks:
    internal:

services:
    client:
        <<: *base-config
        command: list --machines

    server:
        <<: *base-config
        command: list --machines
